import { createSlice } from '@reduxjs/toolkit'

export const formSlice = createSlice({
  name: 'form',
  initialState: {
    title: 'Contact Page',
    formData: {},
  },
  reducer: {
    setFormData(state, action) {
      state.formData = action.payload
    }, // prepare callback function? https://redux-toolkit.js.org/api/createSlice#prepare-callback
  },
})

export default formSlice.reducer

export const { setFormData } = formSlice.actions // this actions automatically generated by redux toolkit
